DROP TABLE IF EXISTS NF; 

CREATE TABLE NF (
Name VARCHAR(100), 
Form VARCHAR(4), 
Y_N CHAR(1), 
Reason VARCHAR(200));

SELECT A1, COUNT(*) FROM T8 
GROUP BY A1 
HAVING COUNT(*) > 1;

SELECT * FROM T8 
WHERE A1 IS NULL;

INSERT INTO NF 
VALUES ('T8','3NF','Y','');

INSERT INTO NF 
VALUES ('T8','BCNF','Y','');

SELECT A1, COUNT(*) FROM T7 
GROUP BY A1 
HAVING COUNT(*) > 1;

SELECT * FROM T7 
WHERE A1 IS NULL;

INSERT INTO NF 
VALUES ('T7','3NF','Y','');

INSERT INTO NF 
VALUES ('T7','BCNF','Y','');

INSERT INTO NF 
VALUES ('T6','3NF','N','not 1NF,some attributes do not exist');

INSERT INTO NF 
VALUES ('T6','BCNF','N','not 3NF');

SELECT A1,A2,A3,A4, COUNT(*) FROM T5 
GROUP BY A1,A2,A3,A4 
HAVING COUNT(*) > 1;

SELECT * FROM T5 
WHERE A1 IS NULL;

SELECT * FROM T5 
WHERE A2 IS NULL;

SELECT * FROM T5 
WHERE A3 IS NULL;

SELECT * FROM T5 
WHERE A4 IS NULL;

SELECT A4, COUNT(*) FROM T5 
GROUP BY A4 
HAVING COUNT(DISTINCT A5) > 1;

INSERT INTO NF 
VALUES ('T5','3NF','N','not 2NF,A4->A5');

INSERT INTO NF 
VALUES ('T5','BCNF','N','not 3NF');

SELECT A1,A2, COUNT(*) FROM T4 
GROUP BY A1,A2 
HAVING COUNT(*) > 1;

SELECT * FROM T4 
WHERE A1 IS NULL;

INSERT INTO NF 
VALUES ('T4','3NF','N','not 1NF,NULL in keys ');

INSERT INTO NF 
VALUES ('T4','BCNF','N','not 3NF');

SELECT A1,A2,A3, COUNT(*) FROM T3 
GROUP BY A1,A2,A3 
HAVING COUNT(*) > 1;

SELECT * FROM T3 
WHERE A1 IS NULL;

SELECT * FROM T3 
WHERE A2 IS NULL;

SELECT * FROM T3 
WHERE A3 IS NULL;

INSERT INTO NF 
VALUES ('T3','3NF','N','not 1NF,duplicate keys ');

INSERT INTO NF 
VALUES ('T3','BCNF','N','not 3NF');

SELECT A1,A2, COUNT(*) FROM T2 
GROUP BY A1,A2 
HAVING COUNT(*) > 1;

SELECT * FROM T2 
WHERE A1 IS NULL;

SELECT * FROM T2 
WHERE A2 IS NULL;

SELECT A2, COUNT(*) FROM T2 
GROUP BY A2 
HAVING COUNT(DISTINCT A3) > 1;

SELECT A2, COUNT(*) FROM T2 
GROUP BY A2 
HAVING COUNT(DISTINCT A4) > 1;

SELECT A2, COUNT(*) FROM T2 
GROUP BY A2 
HAVING COUNT(DISTINCT A5) > 1;

SELECT A1, COUNT(*) FROM T2 
GROUP BY A1 
HAVING COUNT(DISTINCT A3) > 1;

INSERT INTO NF 
VALUES ('T2','3NF','N','not 2NF,A1->A3');

INSERT INTO NF 
VALUES ('T2','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM T1 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM T1 
WHERE K1 IS NULL;

SELECT * FROM T1 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM T1 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K2, COUNT(*) FROM T1 
GROUP BY K2 
HAVING COUNT(DISTINCT A2) > 1;

SELECT K1, COUNT(*) FROM T1 
GROUP BY K1 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K1, COUNT(*) FROM T1 
GROUP BY K1 
HAVING COUNT(DISTINCT A2) > 1;

SELECT A2, COUNT(*) FROM T1 
GROUP BY A2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT A1, COUNT(*) FROM T1 
GROUP BY A1 
HAVING COUNT(DISTINCT A2) > 1;

SELECT A1,A2, COUNT(*) FROM T1 
GROUP BY A1,A2 
HAVING COUNT(DISTINCT K1) > 1;

INSERT INTO NF 
VALUES ('T1','3NF','Y','');

INSERT INTO NF 
VALUES ('T1','BCNF','N','A1,A2->K1');

SELECT * FROM NF;
