DROP TABLE IF EXISTS NF; 

CREATE TABLE NF (
Name VARCHAR(100), 
Form VARCHAR(4), 
Y_N CHAR(1), 
Reason VARCHAR(200));

SELECT K1,K2, COUNT(*) FROM case01 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case01 
WHERE K1 IS NULL;

SELECT * FROM case01 
WHERE K2 IS NULL;

INSERT INTO NF 
VALUES ('case01','3NF','N','not 1NF,duplicate keys ');

INSERT INTO NF 
VALUES ('case01','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case02 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case02 
WHERE K1 IS NULL;

SELECT * FROM case02 
WHERE K2 IS NULL;

INSERT INTO NF 
VALUES ('case02','3NF','N','not 1NF,NULL in keys ');

INSERT INTO NF 
VALUES ('case02','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case03 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case03 
WHERE K1 IS NULL;

SELECT * FROM case03 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case03 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K2, COUNT(*) FROM case03 
GROUP BY K2 
HAVING COUNT(DISTINCT A2) > 1;

INSERT INTO NF 
VALUES ('case03','3NF','N','not 2NF,K2->A2');

INSERT INTO NF 
VALUES ('case03','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case04 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case04 
WHERE K1 IS NULL;

SELECT * FROM case04 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case04 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K1, COUNT(*) FROM case04 
GROUP BY K1 
HAVING COUNT(DISTINCT A1) > 1;

INSERT INTO NF 
VALUES ('case04','3NF','N','not 2NF,K1->A1');

INSERT INTO NF 
VALUES ('case04','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case05 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case05 
WHERE K1 IS NULL;

SELECT * FROM case05 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case05 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

INSERT INTO NF 
VALUES ('case05','3NF','N','not 2NF,K2->A1');

INSERT INTO NF 
VALUES ('case05','BCNF','N','not 3NF');

SELECT K1, COUNT(*) FROM case06 
GROUP BY K1 
HAVING COUNT(*) > 1;

SELECT * FROM case06 
WHERE K1 IS NULL;

SELECT A3, COUNT(*) FROM case06 
GROUP BY A3 
HAVING COUNT(DISTINCT A0) > 1;

INSERT INTO NF 
VALUES ('case06','3NF','N','A3->A0');

INSERT INTO NF 
VALUES ('case06','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case07 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case07 
WHERE K1 IS NULL;

SELECT * FROM case07 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case07 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K2, COUNT(*) FROM case07 
GROUP BY K2 
HAVING COUNT(DISTINCT A2) > 1;

SELECT K1, COUNT(*) FROM case07 
GROUP BY K1 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K1, COUNT(*) FROM case07 
GROUP BY K1 
HAVING COUNT(DISTINCT A2) > 1;

SELECT A2, COUNT(*) FROM case07 
GROUP BY A2 
HAVING COUNT(DISTINCT A1) > 1;

INSERT INTO NF 
VALUES ('case07','3NF','N','A2->A1');

INSERT INTO NF 
VALUES ('case07','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case08 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case08 
WHERE K1 IS NULL;

SELECT * FROM case08 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case08 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K2, COUNT(*) FROM case08 
GROUP BY K2 
HAVING COUNT(DISTINCT A2) > 1;

SELECT K1, COUNT(*) FROM case08 
GROUP BY K1 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K1, COUNT(*) FROM case08 
GROUP BY K1 
HAVING COUNT(DISTINCT A2) > 1;

SELECT A2, COUNT(*) FROM case08 
GROUP BY A2 
HAVING COUNT(DISTINCT A1) > 1;

INSERT INTO NF 
VALUES ('case08','3NF','N','A2->A1');

INSERT INTO NF 
VALUES ('case08','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case09 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case09 
WHERE K1 IS NULL;

SELECT * FROM case09 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case09 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K2, COUNT(*) FROM case09 
GROUP BY K2 
HAVING COUNT(DISTINCT A2) > 1;

SELECT K2, COUNT(*) FROM case09 
GROUP BY K2 
HAVING COUNT(DISTINCT A3) > 1;

SELECT K1, COUNT(*) FROM case09 
GROUP BY K1 
HAVING COUNT(DISTINCT A1) > 1;

INSERT INTO NF 
VALUES ('case09','3NF','N','not 2NF,K1->A1');

INSERT INTO NF 
VALUES ('case09','BCNF','N','not 3NF');

SELECT K1,K2, COUNT(*) FROM case10 
GROUP BY K1,K2 
HAVING COUNT(*) > 1;

SELECT * FROM case10 
WHERE K1 IS NULL;

SELECT * FROM case10 
WHERE K2 IS NULL;

SELECT K2, COUNT(*) FROM case10 
GROUP BY K2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K2, COUNT(*) FROM case10 
GROUP BY K2 
HAVING COUNT(DISTINCT A2) > 1;

SELECT K1, COUNT(*) FROM case10 
GROUP BY K1 
HAVING COUNT(DISTINCT A1) > 1;

SELECT K1, COUNT(*) FROM case10 
GROUP BY K1 
HAVING COUNT(DISTINCT A2) > 1;

SELECT A2, COUNT(*) FROM case10 
GROUP BY A2 
HAVING COUNT(DISTINCT A1) > 1;

SELECT A1, COUNT(*) FROM case10 
GROUP BY A1 
HAVING COUNT(DISTINCT A2) > 1;

SELECT A1,A2, COUNT(*) FROM case10 
GROUP BY A1,A2 
HAVING COUNT(DISTINCT K1) > 1;

INSERT INTO NF 
VALUES ('case10','3NF','Y','');

INSERT INTO NF 
VALUES ('case10','BCNF','N','A1,A2->K1');

INSERT INTO NF 
VALUES ('T8','3NF','N','not 1NF,some attributes do not exist');

INSERT INTO NF 
VALUES ('T8','BCNF','N','not 3NF');

INSERT INTO NF 
VALUES ('T7','1NF','N','Table does not have columns');

INSERT INTO NF 
VALUES ('T10','3NF','N','not 1NF,table does not exist');

INSERT INTO NF 
VALUES ('T10','BCNF','N','not 3NF');

SELECT * FROM NF;
